### ISSUE TITLE
the package can not precompile

### ISSUE THREAD

**Issue by plantstree** [uoa-ems-research/JEMSS.jl#69]
Hi all, I have read your article and I am very encouraged by the role of JEMSS packages in the EMS field. However, when I started using the package, I encountered some problems that prevented JEMSS from working properly.

ERROR: LoadError: UndefVarError: _iszero not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:31
 [2] top-level scope
   @ C:\Users\15956\.julia\packages\MutableArithmetics\mgg9J\src\dispatch.jl:287
 [3] include(mod::Module, _path::String)
   @ Base .\Base.jl:419
 [4] include(x::String)
   @ MutableArithmetics C:\Users\15956\.julia\packages\MutableArithmetics\mgg9J\src\MutableArithmetics.jl:7
 [5] top-level scope
   @ C:\Users\15956\.julia\packages\MutableArithmetics\mgg9J\src\MutableArithmetics.jl:92
 [6] include
   @ .\Base.jl:419 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base .\loading.jl:1554
 [8] top-level scope
   @ stdin:1
in expression starting at C:\Users\15956\.julia\packages\MutableArithmetics\mgg9J\src\dispatch.jl:287
in expression starting at C:\Users\15956\.julia\packages\MutableArithmetics\mgg9J\src\MutableArithmetics.jl:7
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile MutableArithmetics [d8a4904e-b15c-11e9-3269-09a3773c0cb0] to C:\Users\15956\.julia\compiled\v1.8\MutableArithmetics\jl_5F89.tmp.
Stacktrace:
ERROR: Failed to precompile JEMSS [da3c27b9-5cdd-52db-94a3-a4eefd7acbab] to C:\Users\15956\.julia\compiled\v1.8\JEMSS\jl_398C.tmp.
Stacktrace:

Any help to fix this problem is highly appreciated.

**Comment by samridler** [comment]
Hi, thanks for letting me know about this error. I'm working on a fix for it now and will let you know when it's ready.

**Comment by samridler** [comment]
I have fixed the issue in [JEMSS v1.3.4](https://github.com/uoa-ems-research/JEMSS.jl/tree/v1.3.4).
Please update to the newer version with this command from the Julia Pkg REPL:
`pkg> update JEMSS@1.3.4`
And test `using JEMSS` again.
Let me know if you have any more issues.

**Comment by plantstree** [comment]
very thanks
