### ISSUE TITLE
“LoadError: at row 0, column 0 : ArgumentError("number of rows in dims must be > 0, got 0")”

### ISSUE THREAD

**Issue by dsa27solver** [uoa-ems-research/JEMSS.jl#74]
Hello! Can anyone help me to solve this error: 
“LoadError: at row 0, column 0 : ArgumentError("number of rows in dims must be > 0, got 0")”

When I enter the commands:
using JEMSS
include(joinpath(JEMSS.jemssDir, "example/example.jl")) 

in order to run the simulation in the city of Auckland? 

Thank you very much in advance for your help. Best regards. 
Daniel

**Comment by samridler** [comment]
I think the city data may not have been unzipped.
Try running the build step from the Julia REPL in pkg mode (type `]`):
`(@v1.8) pkg> build JEMSS`
Then try run the example again.

**Comment by dsa27solver** [comment]
Exact. Thank you very much Sam!
